---
version: '3.3'
services:
  buildapp:
    build:
      context: buildapp
    volumes:
      - type: volume
        source: data-war
        target: /tmp/war
  bd:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Rr123456
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=Tt123456
    volumes:
      - type: volume
        source: data-db
        target: /App42PaaS-Java-MySQL-Sample/target
    ports:
      - "3306:3306"
    expose:
      - "3306"
  prod:
    image: tomcat:9.0
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: data-war
        target: /usr/local/tomcat/webapps
      - type: bind
        source: ./Config.properties
        target: /usr/local/tomcat/ROOT/Config.properties

volumes:
  data-war:
  data-db:
