---
version: '3.8'
services:
  buildapp:
    build: buildapp
      context: ./buildapp
    volumes:
      - type: volume
         source: share
         target: /App42PaaS-Java-MySQL-Sample/target

volumes:
  share:
